[book]
authors = ["Lukas Benner"]
language = "en"
multilingual = false
src = "src"
title = "Mathematics in Lean"

[build]
build-dir = "out"

[output.html]
git-repository-url = "https://github.com/leanprover/theorem_proving_in_lean4"

[output.html.playground.boring-prefixes]
lean = "# "