[book]
authors = ["Lukas Benner"]
language = "en"
multilingual = false
src = "src"
title = "Mathematics in Lean"

[build]
build-dir = "html"

[output.html]
git-repository-url = "https://github.com/LukasBenner/mathematics_in_lean"

[output.html.playground.boring-prefixes]
lean = "# "